"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MARKERS_PATH = exports.CONFIG_PATH = exports.CONFIG_DIR = void 0;
var node_os_1 = require("node:os");
var node_path_1 = require("node:path");
var CONFIG_DIR = (0, node_path_1.join)((0, node_os_1.homedir)(), ".impulse_sync");
exports.CONFIG_DIR = CONFIG_DIR;
var CONFIG_PATH = (0, node_path_1.join)(CONFIG_DIR, "config.json");
exports.CONFIG_PATH = CONFIG_PATH;
var MARKERS_PATH = (0, node_path_1.join)(CONFIG_DIR, "sync_markers.json");
exports.MARKERS_PATH = MARKERS_PATH;
